services:
  api:
    build:
      context: ./server
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    expose:
      - "3000"
    networks:
      - app-network

  client:
    build:
      context: ./client
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL}
    expose:
      - "3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
